<?php



/**
 * This class defines the structure of the 'sfOauthServerUserScope' table.
 *
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Sat Apr 28 17:26:55 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package	propel.generator.plugins.sfOauthPropelServerPlugin.lib.model.map
 */
class SfoauthserveruserscopeTableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfOauthPropelServerPlugin.lib.model.map.SfoauthserveruserscopeTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return	 void
	 * @throws	 PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('sfOauthServerUserScope');
		$this->setPhpName('Sfoauthserveruserscope');
		$this->setClassname('Sfoauthserveruserscope');
		$this->setPackage('plugins.sfOauthPropelServerPlugin.lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('sfOauthServerUserScope_id_seq');
		// columns
		$this->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'sf_guard_user', 'ID', true, null, null);
		$this->addForeignKey('CONSUMER_ID', 'ConsumerId', 'INTEGER', 'sfOauthServerConsumer', 'ID', true, null, null);
		$this->addColumn('SCOPE', 'Scope', 'VARCHAR', false, 256, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('sfGuardUser', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('user_id' => 'id',), null, null);
		$this->addRelation('Sfoauthserverconsumer', 'Sfoauthserverconsumer', RelationMap::MANY_TO_ONE, array('consumer_id' => 'id',), null, null);
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true',),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SfoauthserveruserscopeTableMap
