<?php


/**
 * Base class that represents a row from the 'sfOauthServerRequestToken' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Thu Apr 26 13:58:38 2012
 *
 * @package    propel.generator.plugins.sfOauthPropelServerPlugin.lib.model.om
 */
abstract class BaseSfoauthserverrequesttoken extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
	const PEER = 'SfoauthserverrequesttokenPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        SfoauthserverrequesttokenPeer
	 */
	protected static $peer;

	/**
	 * The flag var to prevent infinit loop in deep copy
	 * @var       boolean
	 */
	protected $startCopy = false;

	/**
	 * The value for the token field.
	 * @var        string
	 */
	protected $token;

	/**
	 * The value for the secret field.
	 * @var        string
	 */
	protected $secret;

	/**
	 * The value for the consumer_id field.
	 * @var        int
	 */
	protected $consumer_id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the callback field.
	 * @var        string
	 */
	protected $callback;

	/**
	 * The value for the scope field.
	 * @var        string
	 */
	protected $scope;

	/**
	 * The value for the expires field.
	 * @var        int
	 */
	protected $expires;

	/**
	 * The value for the protocole field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $protocole;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        Sfoauthserverconsumer
	 */
	protected $aSfoauthserverconsumer;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUser;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->protocole = 1;
	}

	/**
	 * Initializes internal state of BaseSfoauthserverrequesttoken object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [token] column value.
	 * 
	 * @return     string
	 */
	public function getToken()
	{
		return $this->token;
	}

	/**
	 * Get the [secret] column value.
	 * 
	 * @return     string
	 */
	public function getSecret()
	{
		return $this->secret;
	}

	/**
	 * Get the [consumer_id] column value.
	 * 
	 * @return     int
	 */
	public function getConsumerId()
	{
		return $this->consumer_id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [callback] column value.
	 * 
	 * @return     string
	 */
	public function getCallback()
	{
		return $this->callback;
	}

	/**
	 * Get the [scope] column value.
	 * 
	 * @return     string
	 */
	public function getScope()
	{
		return $this->scope;
	}

	/**
	 * Get the [expires] column value.
	 * 
	 * @return     int
	 */
	public function getExpires()
	{
		return $this->expires;
	}

	/**
	 * Get the [protocole] column value.
	 * 
	 * @return     int
	 */
	public function getProtocole()
	{
		return $this->protocole;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [token] column.
	 * 
	 * @param      string $v new value
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function setToken($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->token !== $v) {
			$this->token = $v;
			$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::TOKEN;
		}

		return $this;
	} // setToken()

	/**
	 * Set the value of [secret] column.
	 * 
	 * @param      string $v new value
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function setSecret($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->secret !== $v) {
			$this->secret = $v;
			$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::SECRET;
		}

		return $this;
	} // setSecret()

	/**
	 * Set the value of [consumer_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function setConsumerId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->consumer_id !== $v) {
			$this->consumer_id = $v;
			$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::CONSUMER_ID;
		}

		if ($this->aSfoauthserverconsumer !== null && $this->aSfoauthserverconsumer->getId() !== $v) {
			$this->aSfoauthserverconsumer = null;
		}

		return $this;
	} // setConsumerId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::USER_ID;
		}

		if ($this->asfGuardUser !== null && $this->asfGuardUser->getId() !== $v) {
			$this->asfGuardUser = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [callback] column.
	 * 
	 * @param      string $v new value
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function setCallback($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->callback !== $v) {
			$this->callback = $v;
			$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::CALLBACK;
		}

		return $this;
	} // setCallback()

	/**
	 * Set the value of [scope] column.
	 * 
	 * @param      string $v new value
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function setScope($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->scope !== $v) {
			$this->scope = $v;
			$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::SCOPE;
		}

		return $this;
	} // setScope()

	/**
	 * Set the value of [expires] column.
	 * 
	 * @param      int $v new value
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function setExpires($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->expires !== $v) {
			$this->expires = $v;
			$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::EXPIRES;
		}

		return $this;
	} // setExpires()

	/**
	 * Set the value of [protocole] column.
	 * 
	 * @param      int $v new value
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function setProtocole($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->protocole !== $v) {
			$this->protocole = $v;
			$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::PROTOCOLE;
		}

		return $this;
	} // setProtocole()

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.
	 *               Empty strings are treated as NULL.
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		$dt = PropelDateTime::newInstance($v, null, 'DateTime');
		if ($this->created_at !== null || $dt !== null) {
			$currentDateAsString = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
			if ($currentDateAsString !== $newDateAsString) {
				$this->created_at = $newDateAsString;
				$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->protocole !== 1) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->token = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->secret = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->consumer_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->user_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->callback = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->scope = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->expires = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->protocole = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->id = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->created_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 10; // 10 = SfoauthserverrequesttokenPeer::NUM_HYDRATE_COLUMNS.

		} catch (Exception $e) {
			throw new PropelException("Error populating Sfoauthserverrequesttoken object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aSfoauthserverconsumer !== null && $this->consumer_id !== $this->aSfoauthserverconsumer->getId()) {
			$this->aSfoauthserverconsumer = null;
		}
		if ($this->asfGuardUser !== null && $this->user_id !== $this->asfGuardUser->getId()) {
			$this->asfGuardUser = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SfoauthserverrequesttokenPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = SfoauthserverrequesttokenPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aSfoauthserverconsumer = null;
			$this->asfGuardUser = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SfoauthserverrequesttokenPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$deleteQuery = SfoauthserverrequesttokenQuery::create()
				->filterByPrimaryKey($this->getPrimaryKey());
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSfoauthserverrequesttoken:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

			if ($ret) {
				$deleteQuery->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSfoauthserverrequesttoken:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SfoauthserverrequesttokenPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSfoauthserverrequesttoken:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// timestampable behavior
				if (!$this->isColumnModified(SfoauthserverrequesttokenPeer::CREATED_AT)) {
					$this->setCreatedAt(time());
				}
				if (!$this->isColumnModified(SfoauthserverrequesttokenPeer::CREATED_AT)) {
					$this->setCreatedAt(time());
				}
			} else {
				$ret = $ret && $this->preUpdate($con);
				// timestampable behavior
				if ($this->isModified() && !$this->isColumnModified(SfoauthserverrequesttokenPeer::CREATED_AT)) {
					$this->setCreatedAt(time());
				}
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSfoauthserverrequesttoken:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				SfoauthserverrequesttokenPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSfoauthserverconsumer !== null) {
				if ($this->aSfoauthserverconsumer->isModified() || $this->aSfoauthserverconsumer->isNew()) {
					$affectedRows += $this->aSfoauthserverconsumer->save($con);
				}
				$this->setSfoauthserverconsumer($this->aSfoauthserverconsumer);
			}

			if ($this->asfGuardUser !== null) {
				if ($this->asfGuardUser->isModified() || $this->asfGuardUser->isNew()) {
					$affectedRows += $this->asfGuardUser->save($con);
				}
				$this->setsfGuardUser($this->asfGuardUser);
			}

			if ($this->isNew() || $this->isModified()) {
				// persist changes
				if ($this->isNew()) {
					$this->doInsert($con);
				} else {
					$this->doUpdate($con);
				}
				$affectedRows += 1;
				$this->resetModified();
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Insert the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @throws     PropelException
	 * @see        doSave()
	 */
	protected function doInsert(PropelPDO $con)
	{
		$modifiedColumns = array();
		$index = 0;

		$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::ID;
		if (null !== $this->id) {
			throw new PropelException('Cannot insert a value for auto-increment primary key (' . SfoauthserverrequesttokenPeer::ID . ')');
		}
		if (null === $this->id) {
			try {				
				$stmt = $con->query("SELECT nextval('sfOauthServerRequestToken_id_seq')");
				$row = $stmt->fetch(PDO::FETCH_NUM);
				$this->id = $row[0];
			} catch (Exception $e) {
				throw new PropelException('Unable to get sequence id.', $e);
			}
		}


		 // check the columns in natural order for more readable SQL queries
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::TOKEN)) {
			$modifiedColumns[':p' . $index++]  = 'TOKEN';
		}
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::SECRET)) {
			$modifiedColumns[':p' . $index++]  = 'SECRET';
		}
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::CONSUMER_ID)) {
			$modifiedColumns[':p' . $index++]  = 'CONSUMER_ID';
		}
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::USER_ID)) {
			$modifiedColumns[':p' . $index++]  = 'USER_ID';
		}
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::CALLBACK)) {
			$modifiedColumns[':p' . $index++]  = 'CALLBACK';
		}
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::SCOPE)) {
			$modifiedColumns[':p' . $index++]  = 'SCOPE';
		}
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::EXPIRES)) {
			$modifiedColumns[':p' . $index++]  = 'EXPIRES';
		}
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::PROTOCOLE)) {
			$modifiedColumns[':p' . $index++]  = 'PROTOCOLE';
		}
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::ID)) {
			$modifiedColumns[':p' . $index++]  = 'ID';
		}
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::CREATED_AT)) {
			$modifiedColumns[':p' . $index++]  = 'CREATED_AT';
		}

		$sql = sprintf(
			'INSERT INTO sfOauthServerRequestToken (%s) VALUES (%s)',
			implode(', ', $modifiedColumns),
			implode(', ', array_keys($modifiedColumns))
		);

		try {
			$stmt = $con->prepare($sql);
			foreach ($modifiedColumns as $identifier => $columnName) {
				switch ($columnName) {
					case 'TOKEN':
						$stmt->bindValue($identifier, $this->token, PDO::PARAM_STR);
						break;
					case 'SECRET':
						$stmt->bindValue($identifier, $this->secret, PDO::PARAM_STR);
						break;
					case 'CONSUMER_ID':
						$stmt->bindValue($identifier, $this->consumer_id, PDO::PARAM_INT);
						break;
					case 'USER_ID':
						$stmt->bindValue($identifier, $this->user_id, PDO::PARAM_INT);
						break;
					case 'CALLBACK':
						$stmt->bindValue($identifier, $this->callback, PDO::PARAM_STR);
						break;
					case 'SCOPE':
						$stmt->bindValue($identifier, $this->scope, PDO::PARAM_STR);
						break;
					case 'EXPIRES':
						$stmt->bindValue($identifier, $this->expires, PDO::PARAM_INT);
						break;
					case 'PROTOCOLE':
						$stmt->bindValue($identifier, $this->protocole, PDO::PARAM_INT);
						break;
					case 'ID':
						$stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
						break;
					case 'CREATED_AT':
						$stmt->bindValue($identifier, $this->created_at, PDO::PARAM_STR);
						break;
				}
			}
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
		}

		$this->setNew(false);
	}

	/**
	 * Update the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @see        doSave()
	 */
	protected function doUpdate(PropelPDO $con)
	{
		$selectCriteria = $this->buildPkeyCriteria();
		$valuesCriteria = $this->buildCriteria();
		BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
	}

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSfoauthserverconsumer !== null) {
				if (!$this->aSfoauthserverconsumer->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSfoauthserverconsumer->getValidationFailures());
				}
			}

			if ($this->asfGuardUser !== null) {
				if (!$this->asfGuardUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUser->getValidationFailures());
				}
			}


			if (($retval = SfoauthserverrequesttokenPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SfoauthserverrequesttokenPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getToken();
				break;
			case 1:
				return $this->getSecret();
				break;
			case 2:
				return $this->getConsumerId();
				break;
			case 3:
				return $this->getUserId();
				break;
			case 4:
				return $this->getCallback();
				break;
			case 5:
				return $this->getScope();
				break;
			case 6:
				return $this->getExpires();
				break;
			case 7:
				return $this->getProtocole();
				break;
			case 8:
				return $this->getId();
				break;
			case 9:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
	{
		if (isset($alreadyDumpedObjects['Sfoauthserverrequesttoken'][$this->getPrimaryKey()])) {
			return '*RECURSION*';
		}
		$alreadyDumpedObjects['Sfoauthserverrequesttoken'][$this->getPrimaryKey()] = true;
		$keys = SfoauthserverrequesttokenPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getToken(),
			$keys[1] => $this->getSecret(),
			$keys[2] => $this->getConsumerId(),
			$keys[3] => $this->getUserId(),
			$keys[4] => $this->getCallback(),
			$keys[5] => $this->getScope(),
			$keys[6] => $this->getExpires(),
			$keys[7] => $this->getProtocole(),
			$keys[8] => $this->getId(),
			$keys[9] => $this->getCreatedAt(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->aSfoauthserverconsumer) {
				$result['Sfoauthserverconsumer'] = $this->aSfoauthserverconsumer->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->asfGuardUser) {
				$result['sfGuardUser'] = $this->asfGuardUser->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SfoauthserverrequesttokenPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setToken($value);
				break;
			case 1:
				$this->setSecret($value);
				break;
			case 2:
				$this->setConsumerId($value);
				break;
			case 3:
				$this->setUserId($value);
				break;
			case 4:
				$this->setCallback($value);
				break;
			case 5:
				$this->setScope($value);
				break;
			case 6:
				$this->setExpires($value);
				break;
			case 7:
				$this->setProtocole($value);
				break;
			case 8:
				$this->setId($value);
				break;
			case 9:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = SfoauthserverrequesttokenPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setToken($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setSecret($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setConsumerId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUserId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCallback($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setScope($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setExpires($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setProtocole($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setId($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCreatedAt($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(SfoauthserverrequesttokenPeer::DATABASE_NAME);

		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::TOKEN)) $criteria->add(SfoauthserverrequesttokenPeer::TOKEN, $this->token);
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::SECRET)) $criteria->add(SfoauthserverrequesttokenPeer::SECRET, $this->secret);
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::CONSUMER_ID)) $criteria->add(SfoauthserverrequesttokenPeer::CONSUMER_ID, $this->consumer_id);
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::USER_ID)) $criteria->add(SfoauthserverrequesttokenPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::CALLBACK)) $criteria->add(SfoauthserverrequesttokenPeer::CALLBACK, $this->callback);
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::SCOPE)) $criteria->add(SfoauthserverrequesttokenPeer::SCOPE, $this->scope);
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::EXPIRES)) $criteria->add(SfoauthserverrequesttokenPeer::EXPIRES, $this->expires);
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::PROTOCOLE)) $criteria->add(SfoauthserverrequesttokenPeer::PROTOCOLE, $this->protocole);
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::ID)) $criteria->add(SfoauthserverrequesttokenPeer::ID, $this->id);
		if ($this->isColumnModified(SfoauthserverrequesttokenPeer::CREATED_AT)) $criteria->add(SfoauthserverrequesttokenPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(SfoauthserverrequesttokenPeer::DATABASE_NAME);
		$criteria->add(SfoauthserverrequesttokenPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Sfoauthserverrequesttoken (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @param      boolean $makeNew Whether to reset autoincrement PKs and make the object new.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
	{
		$copyObj->setToken($this->getToken());
		$copyObj->setSecret($this->getSecret());
		$copyObj->setConsumerId($this->getConsumerId());
		$copyObj->setUserId($this->getUserId());
		$copyObj->setCallback($this->getCallback());
		$copyObj->setScope($this->getScope());
		$copyObj->setExpires($this->getExpires());
		$copyObj->setProtocole($this->getProtocole());
		$copyObj->setCreatedAt($this->getCreatedAt());

		if ($deepCopy && !$this->startCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);
			// store object hash to prevent cycle
			$this->startCopy = true;

			//unflag object copy
			$this->startCopy = false;
		} // if ($deepCopy)

		if ($makeNew) {
			$copyObj->setNew(true);
			$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
		}
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Sfoauthserverrequesttoken Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     SfoauthserverrequesttokenPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new SfoauthserverrequesttokenPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Sfoauthserverconsumer object.
	 *
	 * @param      Sfoauthserverconsumer $v
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSfoauthserverconsumer(Sfoauthserverconsumer $v = null)
	{
		if ($v === null) {
			$this->setConsumerId(NULL);
		} else {
			$this->setConsumerId($v->getId());
		}

		$this->aSfoauthserverconsumer = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Sfoauthserverconsumer object, it will not be re-added.
		if ($v !== null) {
			$v->addSfoauthserverrequesttoken($this);
		}

		return $this;
	}


	/**
	 * Get the associated Sfoauthserverconsumer object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Sfoauthserverconsumer The associated Sfoauthserverconsumer object.
	 * @throws     PropelException
	 */
	public function getSfoauthserverconsumer(PropelPDO $con = null)
	{
		if ($this->aSfoauthserverconsumer === null && ($this->consumer_id !== null)) {
			$this->aSfoauthserverconsumer = SfoauthserverconsumerQuery::create()->findPk($this->consumer_id, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aSfoauthserverconsumer->addSfoauthserverrequesttokens($this);
			 */
		}
		return $this->aSfoauthserverconsumer;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUser(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->asfGuardUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addSfoauthserverrequesttoken($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUser(PropelPDO $con = null)
	{
		if ($this->asfGuardUser === null && ($this->user_id !== null)) {
			$this->asfGuardUser = sfGuardUserQuery::create()->findPk($this->user_id, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->asfGuardUser->addSfoauthserverrequesttokens($this);
			 */
		}
		return $this->asfGuardUser;
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->token = null;
		$this->secret = null;
		$this->consumer_id = null;
		$this->user_id = null;
		$this->callback = null;
		$this->scope = null;
		$this->expires = null;
		$this->protocole = null;
		$this->id = null;
		$this->created_at = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->applyDefaultValues();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all references to other model objects or collections of model objects.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect
	 * objects with circular references (even in PHP 5.3). This is currently necessary
	 * when using Propel in certain daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all referrer objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

		$this->aSfoauthserverconsumer = null;
		$this->asfGuardUser = null;
	}

	/**
	 * Return the string representation of this object
	 *
	 * @return string
	 */
	public function __toString()
	{
		return (string) $this->exportTo(SfoauthserverrequesttokenPeer::DEFAULT_STRING_FORMAT);
	}

	// timestampable behavior
	
	/**
	 * Mark the current object so that the update date doesn't get updated during next save
	 *
	 * @return     Sfoauthserverrequesttoken The current object (for fluent API support)
	 */
	public function keepUpdateDateUnchanged()
	{
		$this->modifiedColumns[] = SfoauthserverrequesttokenPeer::CREATED_AT;
		return $this;
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BaseSfoauthserverrequesttoken:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}

		return parent::__call($name, $params);
	}

} // BaseSfoauthserverrequesttoken
