<?php


/**
 * Base class that represents a query for the 'sfOauthServerUserScope' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Wed Apr 25 11:40:42 2012
 *
 * @method     SfoauthserveruserscopeQuery orderByUserId($order = Criteria::ASC) Order by the user_id column
 * @method     SfoauthserveruserscopeQuery orderByConsumerId($order = Criteria::ASC) Order by the consumer_id column
 * @method     SfoauthserveruserscopeQuery orderByScope($order = Criteria::ASC) Order by the scope column
 * @method     SfoauthserveruserscopeQuery orderById($order = Criteria::ASC) Order by the id column
 *
 * @method     SfoauthserveruserscopeQuery groupByUserId() Group by the user_id column
 * @method     SfoauthserveruserscopeQuery groupByConsumerId() Group by the consumer_id column
 * @method     SfoauthserveruserscopeQuery groupByScope() Group by the scope column
 * @method     SfoauthserveruserscopeQuery groupById() Group by the id column
 *
 * @method     SfoauthserveruserscopeQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     SfoauthserveruserscopeQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     SfoauthserveruserscopeQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     SfoauthserveruserscopeQuery leftJoinsfGuardUser($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfGuardUser relation
 * @method     SfoauthserveruserscopeQuery rightJoinsfGuardUser($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfGuardUser relation
 * @method     SfoauthserveruserscopeQuery innerJoinsfGuardUser($relationAlias = null) Adds a INNER JOIN clause to the query using the sfGuardUser relation
 *
 * @method     SfoauthserveruserscopeQuery leftJoinSfoauthserverconsumer($relationAlias = null) Adds a LEFT JOIN clause to the query using the Sfoauthserverconsumer relation
 * @method     SfoauthserveruserscopeQuery rightJoinSfoauthserverconsumer($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Sfoauthserverconsumer relation
 * @method     SfoauthserveruserscopeQuery innerJoinSfoauthserverconsumer($relationAlias = null) Adds a INNER JOIN clause to the query using the Sfoauthserverconsumer relation
 *
 * @method     Sfoauthserveruserscope findOne(PropelPDO $con = null) Return the first Sfoauthserveruserscope matching the query
 * @method     Sfoauthserveruserscope findOneOrCreate(PropelPDO $con = null) Return the first Sfoauthserveruserscope matching the query, or a new Sfoauthserveruserscope object populated from the query conditions when no match is found
 *
 * @method     Sfoauthserveruserscope findOneByUserId(int $user_id) Return the first Sfoauthserveruserscope filtered by the user_id column
 * @method     Sfoauthserveruserscope findOneByConsumerId(int $consumer_id) Return the first Sfoauthserveruserscope filtered by the consumer_id column
 * @method     Sfoauthserveruserscope findOneByScope(string $scope) Return the first Sfoauthserveruserscope filtered by the scope column
 * @method     Sfoauthserveruserscope findOneById(int $id) Return the first Sfoauthserveruserscope filtered by the id column
 *
 * @method     array findByUserId(int $user_id) Return Sfoauthserveruserscope objects filtered by the user_id column
 * @method     array findByConsumerId(int $consumer_id) Return Sfoauthserveruserscope objects filtered by the consumer_id column
 * @method     array findByScope(string $scope) Return Sfoauthserveruserscope objects filtered by the scope column
 * @method     array findById(int $id) Return Sfoauthserveruserscope objects filtered by the id column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseSfoauthserveruserscopeQuery extends ModelCriteria
{
	
	/**
	 * Initializes internal state of BaseSfoauthserveruserscopeQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Sfoauthserveruserscope', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new SfoauthserveruserscopeQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    SfoauthserveruserscopeQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof SfoauthserveruserscopeQuery) {
			return $criteria;
		}
		$query = new SfoauthserveruserscopeQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key.
	 * Propel uses the instance pool to skip the database if the object exists.
	 * Go fast if the query is untouched.
	 *
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Sfoauthserveruserscope|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ($key === null) {
			return null;
		}
		if ((null !== ($obj = SfoauthserveruserscopePeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
			// the object is alredy in the instance pool
			return $obj;
		}
		if ($con === null) {
			$con = Propel::getConnection(SfoauthserveruserscopePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		if ($this->formatter || $this->modelAlias || $this->with || $this->select
		 || $this->selectColumns || $this->asColumns || $this->selectModifiers
		 || $this->map || $this->having || $this->joins) {
			return $this->findPkComplex($key, $con);
		} else {
			return $this->findPkSimple($key, $con);
		}
	}

	/**
	 * Find object by primary key using raw SQL to go fast.
	 * Bypass doSelect() and the object formatter by using generated code.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    Sfoauthserveruserscope A model object, or null if the key is not found
	 */
	protected function findPkSimple($key, $con)
	{
		$sql = 'SELECT USER_ID, CONSUMER_ID, SCOPE, ID FROM sfOauthServerUserScope WHERE ID = :p0';
		try {
			$stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key, PDO::PARAM_INT);
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
		}
		$obj = null;
		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$obj = new Sfoauthserveruserscope();
			$obj->hydrate($row);
			SfoauthserveruserscopePeer::addInstanceToPool($obj, (string) $row[0]);
		}
		$stmt->closeCursor();

		return $obj;
	}

	/**
	 * Find object by primary key.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    Sfoauthserveruserscope|array|mixed the result, formatted by the current formatter
	 */
	protected function findPkComplex($key, $con)
	{
		// As the query uses a PK condition, no limit(1) is necessary.
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKey($key)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKeys($keys)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->format($stmt);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(SfoauthserveruserscopePeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(SfoauthserveruserscopePeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the user_id column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByUserId(1234); // WHERE user_id = 1234
	 * $query->filterByUserId(array(12, 34)); // WHERE user_id IN (12, 34)
	 * $query->filterByUserId(array('min' => 12)); // WHERE user_id > 12
	 * </code>
	 *
	 * @see       filterBysfGuardUser()
	 *
	 * @param     mixed $userId The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function filterByUserId($userId = null, $comparison = null)
	{
		if (is_array($userId)) {
			$useMinMax = false;
			if (isset($userId['min'])) {
				$this->addUsingAlias(SfoauthserveruserscopePeer::USER_ID, $userId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($userId['max'])) {
				$this->addUsingAlias(SfoauthserveruserscopePeer::USER_ID, $userId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(SfoauthserveruserscopePeer::USER_ID, $userId, $comparison);
	}

	/**
	 * Filter the query on the consumer_id column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByConsumerId(1234); // WHERE consumer_id = 1234
	 * $query->filterByConsumerId(array(12, 34)); // WHERE consumer_id IN (12, 34)
	 * $query->filterByConsumerId(array('min' => 12)); // WHERE consumer_id > 12
	 * </code>
	 *
	 * @see       filterBySfoauthserverconsumer()
	 *
	 * @param     mixed $consumerId The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function filterByConsumerId($consumerId = null, $comparison = null)
	{
		if (is_array($consumerId)) {
			$useMinMax = false;
			if (isset($consumerId['min'])) {
				$this->addUsingAlias(SfoauthserveruserscopePeer::CONSUMER_ID, $consumerId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($consumerId['max'])) {
				$this->addUsingAlias(SfoauthserveruserscopePeer::CONSUMER_ID, $consumerId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(SfoauthserveruserscopePeer::CONSUMER_ID, $consumerId, $comparison);
	}

	/**
	 * Filter the query on the scope column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByScope('fooValue');   // WHERE scope = 'fooValue'
	 * $query->filterByScope('%fooValue%'); // WHERE scope LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $scope The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function filterByScope($scope = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($scope)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $scope)) {
				$scope = str_replace('*', '%', $scope);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(SfoauthserveruserscopePeer::SCOPE, $scope, $comparison);
	}

	/**
	 * Filter the query on the id column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterById(1234); // WHERE id = 1234
	 * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
	 * $query->filterById(array('min' => 12)); // WHERE id > 12
	 * </code>
	 *
	 * @param     mixed $id The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(SfoauthserveruserscopePeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query by a related sfGuardUser object
	 *
	 * @param     sfGuardUser|PropelCollection $sfGuardUser The related object(s) to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function filterBysfGuardUser($sfGuardUser, $comparison = null)
	{
		if ($sfGuardUser instanceof sfGuardUser) {
			return $this
				->addUsingAlias(SfoauthserveruserscopePeer::USER_ID, $sfGuardUser->getId(), $comparison);
		} elseif ($sfGuardUser instanceof PropelCollection) {
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
			return $this
				->addUsingAlias(SfoauthserveruserscopePeer::USER_ID, $sfGuardUser->toKeyValue('PrimaryKey', 'Id'), $comparison);
		} else {
			throw new PropelException('filterBysfGuardUser() only accepts arguments of type sfGuardUser or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the sfGuardUser relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function joinsfGuardUser($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('sfGuardUser');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'sfGuardUser');
		}

		return $this;
	}

	/**
	 * Use the sfGuardUser relation sfGuardUser object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfGuardUserQuery A secondary query class using the current class as primary query
	 */
	public function usesfGuardUserQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinsfGuardUser($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'sfGuardUser', 'sfGuardUserQuery');
	}

	/**
	 * Filter the query by a related Sfoauthserverconsumer object
	 *
	 * @param     Sfoauthserverconsumer|PropelCollection $sfoauthserverconsumer The related object(s) to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function filterBySfoauthserverconsumer($sfoauthserverconsumer, $comparison = null)
	{
		if ($sfoauthserverconsumer instanceof Sfoauthserverconsumer) {
			return $this
				->addUsingAlias(SfoauthserveruserscopePeer::CONSUMER_ID, $sfoauthserverconsumer->getId(), $comparison);
		} elseif ($sfoauthserverconsumer instanceof PropelCollection) {
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
			return $this
				->addUsingAlias(SfoauthserveruserscopePeer::CONSUMER_ID, $sfoauthserverconsumer->toKeyValue('PrimaryKey', 'Id'), $comparison);
		} else {
			throw new PropelException('filterBySfoauthserverconsumer() only accepts arguments of type Sfoauthserverconsumer or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the Sfoauthserverconsumer relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function joinSfoauthserverconsumer($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Sfoauthserverconsumer');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Sfoauthserverconsumer');
		}

		return $this;
	}

	/**
	 * Use the Sfoauthserverconsumer relation Sfoauthserverconsumer object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    SfoauthserverconsumerQuery A secondary query class using the current class as primary query
	 */
	public function useSfoauthserverconsumerQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinSfoauthserverconsumer($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Sfoauthserverconsumer', 'SfoauthserverconsumerQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Sfoauthserveruserscope $sfoauthserveruserscope Object to remove from the list of results
	 *
	 * @return    SfoauthserveruserscopeQuery The current query, for fluid interface
	 */
	public function prune($sfoauthserveruserscope = null)
	{
		if ($sfoauthserveruserscope) {
			$this->addUsingAlias(SfoauthserveruserscopePeer::ID, $sfoauthserveruserscope->getId(), Criteria::NOT_EQUAL);
		}

		return $this;
	}

} // BaseSfoauthserveruserscopeQuery