<?php



/**
 * Skeleton subclass for representing a row from the 'sfOauthServerUserScope' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Tue Apr 24 12:48:25 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package	propel.generator.lib.model
 */
class Sfoauthserveruserscope extends BaseSfoauthserveruserscope
{
	public function preDelete(PropelPDO $con = null)
	{
		// We have to delete also the current access tokens and code tokens
		$tokens = sfOauthServerAccessTokenQuery::create()->where('consumer_id = ?', $this->getConsumerId())->andWhere('user_id = ?', $this->getUserId())->execute();
		foreach($tokens as $token)
			$token->delete();

		$tokens = sfOauthServerRequestTokenQuery::create()->where('consumer_id = ?', $this->getConsumerId())->andWhere('user_id = ?', $this->getUserId())->execute();
		foreach($tokens as $token)
			$token->delete();

	}
} // Sfoauthserveruserscope
