<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sfOauthServerDeveloper' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Tue Apr 24 12:48:25 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package	propel.generator.lib.model
 */
class SfoauthserverdeveloperQuery extends BaseSfoauthserverdeveloperQuery
{

} // SfoauthserverdeveloperQuery
